Nasal/engine.nas

Fixes controlling the mixture with the keyboard.

Fix controlling mixture with m and M keys

---

c172-checklists.xml

This fixes #4. Before merging in Github, please do `git pull` (or fetch) and then `git checkout bug-4`. Then start FG to test the changes.

Add missing items to checklists (fixes #4)

---

c172p-detailed-set.xml

* Added the new tag <variant-of> Information
* Complete translation in the spanish translation

Formal changes in the c172p-detailed-set.xml file

---

Dialogs/c172p-menu.xml
Nasal/avionics.nas
Nasal/c172p-kap140.nas
Nasal/engine.nas
Nasal/shadow.nas
c172p-detailed-set.xml
c172p-keyboard.xml

Move some code in the -set.xml file to separate files + fix FlightGear version check for ALS shadow volume

Set file refactoring

---

Tutorials/startup.xml

To start the C172 you now have to have the correct mixture, set the master
switch and you may even have to prime the engine. This commit adds these points
to the engine start-up tutorial.

Update start-up tutorial.

---

Models/c172p-detailed.xml
Nasal/c172p-detailed.nas
c172p-detailed-set.xml

Hopefully this is all done and I can move on. Someone,  please take a look and merge when satisfied.

MP model fix

---

Nasal/physics.nas
c172p-detailed-set.xml
c172p.xml

Dany, please confirm I got this correct. I added the all changes by hand and refactored physics.nas a bit.

New FDM damage effects caused by overspeed and g-forces.

---

README.md

With the assumption that the "Spin and stall" feature (alternative FDM) will be included.

README, dany93 contribution

---

c172p-detailed-set.xml
c172p-fdm-dany93.xml
c172p.xml

* Fixes turning on master battery and alternator in the checklists
* Remove the JSBSim error about the `fcs/mixture-pos-norm` property
Please test the master switches and the mixture. If your git status is clean:
1. `git fetch origin`
2. `git checkout misc-bug-fixes`

Misc bug fixes

---

c172-checklists.xml

This got accidentally reverted in my other change to the same file, duh, sorry about that.

another try, now trying not to revert it afterwards :-)

---

Models/Effects/interior/c172p-interior.eff
Nasal/flashlight.nas
c172p-set.xml
gui/dialogs/c172p-menu.xml

It's done. Requires a new fgdata pull as of today.

ALS Flashlight

---

c172p-set.xml

Status: Advanced production
Rating:
- FDM :star: :star: :star: :star:
- Systems :star: :star: :star: :star: :star:
- Cockpit :star: :star: :star: :star: :star:
- Model :star: :star: :star: :star:

Updated c172p-set.xml (authors, status, rating)

---

c172-checklists.xml

ok, i think we got it this time... thanks for the help onox! :smile_cat:

shorten EMERCENCY checklist titles to fit menu selector

---

Nasal/flashlight.nas

Clean up the code in `Nasal/flashlight.nas` a bit by using `math.mod()`.

Use math.mod()

---

Models/c172p.xml
Nasal/physics.nas
c172p.xml

Amphibious, front and rear gears: correction for Z-position, spring coeff and animations for suspension.
https://github.com/Juanvvc/c172p-detailed/issues/214#issuecomment-109620671
https://github.com/Juanvvc/c172p-detailed/issues/254#issuecomment-110048566
https://github.com/Juanvvc/c172p-detailed/issues/254#issuecomment-110148086

Amphibious, gear spring and animation (front and rear)

---

Models/Effects/pontoon/left-spray.xml
Models/Effects/pontoon/left-wake.xml
Models/Effects/pontoon/left_ground.xml
Models/Effects/pontoon/middle-wake.xml
Models/Effects/pontoon/right-spray.xml
Models/Effects/pontoon/right-wake.xml
Models/Effects/pontoon/right_ground.xml
Nasal/physics.nas
Systems/c172p-hydrodynamics.xml
Systems/flight-recorder/components/effects.xml
Systems/gearAGL.xml
c172p-set.xml

@wlbragg Just like PR #283 except without the merge commits.

MP record ground effects

---

Nasal/physics.nas

Fixes #284 and #288 
This should take care of both issues.

Propwash fades on takeoff, fix propwash not disappearing

---

c172-sound.xml

Fixes #264 
Added sound effects for the pontoons/floats using the existing `water-fast.wav` sound.
The volume is rather subtle. What do you think?

Added water sound from the pontoons/floats at speed.

---

Models/Interior/Panel/Instruments/EGT/EGT.xml
Models/Interior/Panel/Instruments/asi/asi.xml
Models/Interior/Panel/Instruments/mag-compass/mag-compass.xml

Use knob animation for EGT Bug and remove tooltips of ASI and compass

---

Systems/c172p-hydrodynamics.xml

cf this issue https://github.com/Juanvvc/c172p-detailed/issues/326#issuecomment-114518061
For merging  this in the current 160 hp version.

hydrodynamics: soften the behavior

---

Models/Interior/Yoke/yoke.xml
gui/dialogs/c172p-menu.xml

Add tooltip and menu item for showing/hiding yokes

---

Models/c172p.xml

Add shadow and flashlight effect to Ceiling Speaker

---

c172p-set.xml

This is just a trivial change to some of the help text that no-longer applies now this replaces the fgdata c172p

Update help text to reflect this is the core c172p

---

Nasal/electrical.nas
Systems/flight-recorder/components/systems-instruments.xml

flight recorder: Add battery charge

---

Models/Interior/Panel/Instruments/kap140/KAP140TwoAxisAlt.xml

If this looks good hope it can be merged... thanks...

Begin to add more autopilot tooltips

---

Models/c172p.xml
c172-help.xml
c172p-keyboard.xml
c172p-set.xml

Fixes #344
Use r to move water rudders up, R to move them down.

Animate water rudders, move up/down with r/R, transmit over MP

---

Nasal/c172p.nas
Nasal/electrical.nas
Nasal/engine.nas

Fixes #367. Please wait until user "someguy" on the forum has reported it fixes his problem.

Fix some usage of old engine properties

---

Models/c172p.xml

Remove shadow from TrimWheel object, fixes #250

---

Models/Interior/Panel/Instruments/kx165/kx165-1.xml
Models/Interior/Panel/Instruments/kx165/kx165-2.xml

Fix KHz dial of NAV1/2 to go from 117.95 to 117.00 instead of 118.00

---

c172-checklists.xml
c172-help.xml

Add items from #269 to checklists for float planes.
@tigert @wezzer What should be the takeoff speed and landing speed for float planes?

checklist: Add items for float planes

---

c172p-set.xml

Set some defaults

---

Nasal/engine.nas
Panels/Instruments/egt-ff-c172s.xml
Panels/c172-610x-panel.xml
Systems/NAVandGSfilters.xml
Systems/engine.xml

Fixes https://github.com/Juanvvc/c172p-detailed/issues/338#issuecomment-118703532

Bug 338 engine

---

README.md

Adding names and more information about the work done by @onox and @Juanvvc (you guys deserve more credit than just having your nickname inside a parenthesis). I also added the name of @wkitty42.
So before merging, each one of you please confirm you are fine with these modifications as I don't want to force anyone here to add more information than they are comfortable with, okay?

adding names to README

---

Models/c172p.xml
Nasal/c172p.nas
Systems/pax.xml
c172p-set.xml

Transmit co-pilot's and passengers' presence over MP

---

Models/Effects/shadow/3damphibiousshadow.xml
Models/Effects/shadow/3dbush26shadow.xml
Models/Effects/shadow/3dbush36shadow.xml
Models/Effects/shadow/3dbushdefshadow.xml
Models/Effects/shadow/3dpontoonshadow.xml
Models/c172p.xml

Disable 3D shadow for other c172p in MP because of #387

---

Tutorials/landing.xml

Fixes #442 
I think this is all that is needed. Tested it using "Complex start up procedures" checked and "Start with engine running" not checked.

Fix straight-in-landing tutorial

---

Models/Interior/Panel/Instruments/BatteryGauge/BatteryGauge.xml

fixing bug 463

---

Nasal/c172p.nas
Systems/c172p-skis.xml
Systems/flight-recorder/components/gear-skis.xml
Systems/ground-effects.xml

Getting rid of some commented out, unused code.

Cleanup miscellaneous files.

---

Models/Effects/damage/damage.xml

Fix wrong path to parent effect

---

Nasal/c172p.nas
c172p-set.xml
gui/dialogs/aircraft-dialog.xml

implementing the option to save fuel state

---

Models/Effects/interior/c172p-interior-radiance.eff
Models/Effects/interior/c172p-interior.eff
Models/c172p.xml

Fix irradiance mapping.

---

Nasal/c172p.nas
c172p-set.xml
gui/dialogs/aircraft-dialog.xml

implementing #164

---

Nasal/electrical.nas
c172p-set.xml
c172p.xml

FDM: Disable movement of flaps if voltage is too low

---

Models/c172p.xml
c172p-set.xml

Fixes #423 and #424.
I had to make a local copy of the `walker-include.xml` in order to change the gender of our walker into the correct one. The model is still shared though.

fixing some walker bugs

---

Models/Effects/exterior/exterior-glass-reflection.eff

I think it is the shape of our glass that is limiting this effect. Even with that said, I think this is pretty good.
See #314

Adjust exterior glass reflection.

---

Systems/flight-recorder/components/switches.xml

flight recorder: Fix property type of magnetos

---

c172-checklists.xml

Added a checklist for preflight inspection, removed twice contained items (in ```Preflight``` and ```Before starting engine```, and expanded the Securing aircraft checklist.

"Preflight Inspection" checklists

---

NEWS.md

adding NEWS.md

---

Models/Exterior/chock/chock.xml
Models/Exterior/rbf/rbf.xml
Models/Exterior/tiedowns/tiedownL.xml
Models/Exterior/tiedowns/tiedownR.xml
Models/Exterior/wooden-chock/woodenchock.xml

No-previews to effect and accessory models.

---

Systems/glass-rain.xml

Minor change, gets rid of momentary downward movement of rain.

Adjust windshield rain RPM X and Z.

---

Tutorials/preflight.xml
c172-checklists.xml

Fixes problem in PR https://github.com/Juanvvc/c172p-detailed/pull/580#issuecomment-160446864
Fixing checklists, consistently spelling tie-down instead of tiedown on checklists and preflight tutorial

fixing small things concerning pre-flight inspection

---

Models/c172p.xml

I just happened to notice this.

Remove typo.

---

Models/c172p.xml

I assume this is the correct fix for this issue?

Change blend on prop at high speed to half.

---

Models/Interior/Panel/Flaps/flaps.xml

Bug 616: Give flaps control a vertical drag direction

---

Models/Exterior/tiedowns/tiedownL.xml
Models/Exterior/tiedowns/tiedownR.xml
Models/Exterior/tiedowns/tiedownT.xml
Models/c172p.xml
Nasal/c172p.nas
Nasal/tiedowns.nas
Systems/c172p-ground-effects.xml
Systems/ground-effects.xml
c172p-set.xml
gui/dialogs/aircraft-dialog.xml

Bug 627: Securing attributes aren't visible over multiplayer

---

Nasal/engine.nas

This allows joysticks (etc.) to control it more easily.
(First time collaborating here, let me know if I need to do anything differently!)

Point controls.stepMagnetos to new property

---

Tutorials/preflight.xml
Tutorials/startup.xml

See #628
Fix throttle setting, add lights off and master/alternator off in initial step.

Bug 628: Startup tutorial

---

Nasal/c172p.nas

Bug 636: Remove some unneeded Nasal code

---

Systems/bushkit.xml
c172p.xml

Bug 638: Fix indices of pointmasses of skis and 180 HP engine

---

c172-help.xml
c172p-keyboard.xml

IMHO this is the easiest way to show/hide the yoke
Signed-off-by: Jonathan Schellhase

Use the "y"-key to show/hide yokes

---

c172p.xml

FDM: Set fuel type to AVGAS and reduce max cap to 129.43 lbs

---

Models/Effects/damage/nose_gear.xml
Models/Effects/damage/tail.xml
Models/Effects/damage/wing-left.xml
Models/Effects/damage/wing-right.xml

Fixes #295 
I think this covers it.

Sparks not influenced by available light.

---

Nasal/physics.nas

Fixes #607 
Uses unit 11 or 12 WOW and AGL < 5 in physics loop.

Bug 607 - Kill engine when upside down.

---

gui/dialogs/aircraft-dialog.xml

Bug 664: Improve layout of Aircraft Options dialog

---

WebPanel/EGT.svg

* Also fix EGT needle's visual so it goes under the black "lid" of the gauge glass.
* Fix helper needle to reach to the adjustment screw
* Align both needles' angles consistently.

Adjust helper needle angle to match the EGT needle

---

WebPanel/c172p-webpanel.html

added two columns which will later be used for radiostack (see fgdata/Phi/examples/radio.*) but that needs more styling work still so empty for now.

adjust columns so gauges fit better on widescreen monitor

---

Systems/c172p-ground-effects.xml

Bug 673: Add some damping to the PID controllers of the tiedowns

---

Nasal/physics.nas

Bug 680: Do not kill engine if "Damage" is disabled

---

NEWS.md

Bug 471: Update NEWS.md with features and fixed added in 2016.1 release

---

NEWS.md
README.md

Last minute updates if we decide to update the release!

Update contributors and accomplishments list (readme and news)

---

Systems/flight-recorder/components/systems-instruments.xml
Systems/ground-effects.xml
Systems/indicated-airspeed.xml
gui/dialogs/aircraft-dialog.xml

Fixes #710 Flight recorder should work as well.

Bug 710: Disable ASI while pitot tube cover is visible

---

c172p.xml

In response to https://github.com/Juanvvc/c172p-detailed/issues/721#issue-135823068.
Comment by algefaen.

FDM : decrease rudder authority

---

Models/Effects/interior/c172p-interior-radiance.eff
Models/c172p.xml

Lets try this again.
Should close issue #704

Bug 704: ceiling looks black

---

Models/Interior/Panel/Flaps/flaps.xml

Bug 732: Make flap lever switch object draggable and scrollable

---

Models/Interior/Pedals/pedals.xml

Fixes #752 by simply reversing the translation of the rudder pedals

reversing rudder pedal translation direction

---

c172p-set.xml

This pull request:
* adds the Italian translation of the aircraft description;
* fixes a typo in the credits (Israel Hernandez's nickname is "IAHM-COL").

c172p-set.xml: add Italian translation, fix wrong nickname in credits

---

c172p-set.xml

Fixes https://github.com/Juanvvc/c172p-detailed/issues/773

removing the AI serviceable property from the set file

---

Models/Interior/Panel/Instruments/clock/clock.xml
Systems/instruments.xml

clock now displays local time

---

Models/Interior/Yoke/yoke.xml

animation to YokeMain

---

Models/c172p.xml

Raising max distance of InstrumentsGroup and ControlsGroup to 35m

Raising max distance of InstrumentsGroup and ControlsGroup to 35m

---

Nasal/c172p.nas

autostart now recharges the battery

---

Nasal/light-manager.nas
Systems/als-lights.xml
c172p-set.xml

Please review and critique. I attempted to adjust the lights somewhat, but it is pssible they could be positioned more accurately.
I extended the lights to 4, landing, taxi, 2 x nav.
@onox, I didn't refactor the code to use the UpdateLoop you used in the tiedown code (feel free to if you think it best).
Why is the UpdateLoop a better choice?

Bug 811: ALS external view taxi or landing lights

---

Models/Interior/Baggages/suitcase1.xml
Models/Interior/Baggages/suitcase2.xml
Models/Interior/FE-ELT/elt.xml
Models/Interior/FE-ELT/fe.xml
Models/Interior/FE-ELT/fe2.xml

Bug #872
Pleas beware when testing, the shadow may not play nice with the existing interior cockpit shadow as they are in different coordinate space.

Add interior shadow effect to suitcases and fe-elt.

---

gui/dialogs/aircraft-dialog.xml

This reverts a change in PR #869.

Bug 866: Add back checkbox to display/hide shadow

---

Models/c172p.xml
c172p-views.xml

Adding IFR view

---

Nasal/c172p.nas

Changed the way to remove a static model a bit. Simply test if you can still remove the ground equipment.

Improve method of removing static models a bit

---

Models/Effects/exterior/bumpspec-pontoon.eff
Models/Effects/exterior/bumpspec.eff

Using the fresnel settings from https://github.com/c172p-team/c172p-detailed/issues/876#issuecomment-264672126

Bug 876: Modify bumpspec for fresnel effect

---

Systems/instruments.xml

Bug 900: serviceable of comm0/comm1/DME/transponder depends on electrical output

---

c172p.xml

Deleting the  'aileron pos averaged' branch (to modify the branch name) closed the #933 pull request.

931 aileron pos averaged

---

Models/Interior/Yoke/yoke.xml

Increasing range of rotation of the yoke animation

---

Models/Interior/Yoke/yoke.xml

changing range of yoke rotation to 90 degrees

---

c172p.xml

See issue https://github.com/c172p-team/c172p-detailed/issues/944

FDM adjustments: elevator stall table, side force rudder, adverse yaw

---

Systems/c172p-ground-effects.xml
c172-sound.xml
gui/dialogs/aircraft-dialog.xml

Fix visible yellow sparks while not moving if landed on a moving object

---

c172p-set.xml
c172p.xml

add spiraling propwash effect (new)

---

Systems/views.xml

Enable walker views if and only if walker is switched on

---

Nasal/engine.nas

Fix setting magnetos to both when walking backwards with walker

---

Nasal/views.nas
c172-help.xml
c172p-keyboard.xml
c172p-set.xml

Use shift + q to reset camera to the default position and orientation

---

c172p.xml

Issue #993 - fixed warnings generated by the AI wake feature.

---

c172-help.xml

Adding flashlight shortcut to help file

Adding flashlight shortcut to help file

---

Models/Interior/Panel/Instruments/dme/dme.xml

Fixes #1005 
Refer to #1005 for more detail & informal test case.

Issue 1005: DME Hold Mode not working from NAV2.

---

Tutorials/landing.xml

The exit condition by latitude is wrong in 2017.3.1

Correct the latitude

---

Thanks

thanking for CC0 sounds sources.
@onox I added these to the `Thanks` file instead of creating a new `README.md` inside `/Sounds` since we already used the `Thanks` file for exactly this sort of thing.

thanking for CC0 sounds sources

---

Models/Effects/shadow/3damphibiousshadow.xml
Models/Effects/shadow/3dbush26shadow.xml
Models/Effects/shadow/3dbush36shadow.xml
Models/Effects/shadow/3dbushdefshadow.xml
Models/Effects/shadow/3dpontoonshadow.xml
Models/Effects/shadow/3dskishadow.xml
Nasal/physics.nas
Systems/c172p-damage.xml
gui/dialogs/aircraft-dialog.xml

Fixes #1050 
Fixes #308
Fixes #913 
This PR also correct the issue of a broken shadow when aircraft is at extreme orientations.

issue-1050

---

CONTRIBUTING.md

Add phrase about 'good first bug' label to contributing file

Add phrase about 'good first bug' label to contributing file

---

Models/Interior/Panel/Instruments/mag-compass/mag-compass.xml

Add factor to mag-compass

---

Models/Interior/Panel/Instruments/tc/tc.xml
c172p-set.xml
c172p.xml

FDM: make the aircraft less sensitive to controls

---

Systems/c172p-damage.xml
c172-sound.xml

FDM: decrease one-wing-damage factor

---

CONTRIBUTING.md

Fixed find shell line to find tabs in xml files

---

c172p.xml

FDM: pitch moment due to flap deflection

---

Models/Interior/Panel/Instruments/dme/dme.xml
Models/Interior/Panel/Instruments/dme/ki266.xml
Models/Interior/Panel/Instruments/kap140/KAP140TwoAxisAlt.xml
Models/Interior/Panel/Instruments/kma20/kma20.xml
Models/Interior/Panel/Instruments/kr87-adf/kr87.xml
Models/Interior/Panel/Instruments/kt76a/kt76a.xml
Models/Interior/Panel/Instruments/kx165/kx165-1.xml
Models/Interior/Panel/Instruments/kx165/kx165-2.xml

Fixes #1001 
Remaining issue: dual input data for the same tooltip is partially working (NAV1&2 volume knob).  The volume is always refreshed, but not the push/pull state.

Issue 1001: Missing tooltips / hovered information

---

c172p-set.xml
c172p.xml

Fixes #1114
Fixes #1113 
See #1112

FDM: fix aileron trim preset, introduce spiral propwash tuning

---

c172p-set.xml

Fixes https://github.com/c172p-team/c172p/issues/1112

setting propwash coefficient to 0.5

---

c172p-set.xml
c172p.xml

FDM: P-factor (propeller effect) change from 5 to 59 or 60

---

Tutorials/altimeter.xml
Tutorials/engine-failure.xml
Tutorials/landing.xml
Tutorials/pattern.xml
Tutorials/preflight.xml
Tutorials/radios.xml
Tutorials/runup.xml
Tutorials/securing.xml
Tutorials/startup.xml
Tutorials/takeoff.xml
Tutorials/taxiing.xml

@wlbragg if you would like to test and see if you get that issue that I mentioned?

Preflight to runup tutorials completed

---

Tutorials/preflight.xml
Tutorials/securing.xml
c172-checklists.xml
gui/dialogs/aircraft-dialog.xml

Checklists: securing aircraft fixed

---

Models/c172p.xml
Tutorials/preflight.xml
Tutorials/securing.xml
c172-checklists.xml
c172p-set.xml

@wlbragg this PR fixes all the stuff that was left from @legoboyvdlp's last PR. Please go through both preflight and securing tutorials. Then also go through both preflight and securing checklists. Should be ready to merge.

Checklist and tutorials

---

c172p.xml

Fixes #1203 
Probably should be in the release - could potentially break the logic somewhere.

Fix issue-1203

---

c172p-set.xml

setting model and FDM ratings to 5 stars

New rating

---

Models/c172p.xml
c172p.xml

Fixes #1068 
Ready for merging... I hope?

Fix #1068: brake influences NWS and the nose wheel steering is centered if the strut is uncompressed

---

Nasal/c172p.nas

Fixes #1206 
This was an easy fix as we had the auto-mixture function working already.
Please test and merge when ready.

Use auto-mixture in autostart function

---

c172p.xml

FDM, pitching moment at zero alpha

---

Systems/c172p-heat.xml
Systems/c172p-hydrodynamics.xml
c172p.xml

Correct JSBSim tag errors

---

Models/c172p.xml
Systems/c172p-ground-effects.xml

Wheel spin rolling animation

---

Systems/bushkit.xml

Found this bug while working on friction code. It's unrelated to friction.
Ready to merge.

Bug in float determination code

---

Nasal/engine.nas
Tutorials/amphibious-landing.xml
Tutorials/amphibious-night.xml
Tutorials/amphibious-takeoff.xml
Tutorials/engine-failure.xml
Tutorials/landing.xml
Tutorials/pattern.xml
Tutorials/runup.xml
Tutorials/startup.xml
Tutorials/takeoff.xml
Tutorials/taxiing.xml

Fix issue of cowl plug being stuck in some tutorial

---

c172p.xml

FDM: change P-factor (from 60 to 15)

---

Nasal/tiedowns.nas

Fixes #1274 
I think this is fixed.
@legoboyvdlp please confirm before merging. Once merged we can cherry pick it to the release.

Regress removal of fdm-init listener portion of commit a552abb

---

Models/Effects/exterior/bumpspec-pontoon.eff
Models/Effects/exterior/dirt-fuselage.eff
Models/Effects/exterior/dirt-leading-edge.eff
Models/Effects/exterior/dirt-tail.eff
Models/Effects/exterior/dirt-wing.eff
Models/Effects/skis/effectsMetal.eff
Models/c172p.xml

Fixes #1282 
Tested - ready to merge

Fix xy-plane and missing texture error messages

---

Systems/c172p-ground-effects.xml

Correct a segfault caused when you lower and then raise the amphibious gear on land

---

c172p-set.xml

Issue-1295

---

Models/Interior/Panel/Instruments/gear/gear-ctl.xml

Fix amphibious gear control breaker logic

---

c172p.xml

Fix pitch oscillations at rest, Brakes ON, with pure crosswind

---

Nasal/avionics.nas

Fixes #1304 
Needs to be backported to Release 2019.1 and notify @zakalawe or Stuart on the mailing list to update fgdata c172p and appropriate releases.

Remove unneeded semicolon

---

c172p-amphibious-set.xml
c172p-bush26-set.xml
c172p-bush36-set.xml
c172p-float-set.xml
c172p-ski-set.xml

everything in FG is using xml version 1.0... research shows xml version 1.1 is problematic and was effectively experimental... prevailing thoughts in the industry is that xml version 1.1 should be considered a failed experiment and handled as if it never existed...
reference this mailing list thread and the follow-ups: [[xml] When will you support xml version 1.1?](https://mail.gnome.org/archives/xml/2007-June/msg00014.html)

Wkitty42 patch 1

---

Tutorials/preflight.xml

Fixing minor spelling mistake in preflight tutorial.

Fix minor spelling mistake in tutorial

---

Tutorials/radios.xml

Fixes #1258 
As this tutorial didn't take long time I guess just using battery is enough. Otherwise we may can also start the engine.

Starting with battery and avionic-master on for tutorial

---

Models/Interior/Panel/Instruments/magneto-switch/magneto-switch.xml

Fixes #1322 
@gilbertohasnofb I think this is good.

Turn magnetos on when using ignition key

---

Tutorials/altimeter.xml
Tutorials/amphibious-landing.xml
Tutorials/amphibious-night.xml
Tutorials/amphibious-takeoff.xml
Tutorials/engine-failure.xml
Tutorials/landing.xml
Tutorials/pattern.xml
Tutorials/preflight.xml
Tutorials/radios.xml
Tutorials/runup.xml
Tutorials/securing.xml
Tutorials/startup.xml
Tutorials/takeoff.xml
Tutorials/taxiing.xml

Fixes the ticket just opened on sourceforge.

Repair aircraft at the start of each tutorial

---

Models/Interior/Panel/Instruments/AI/AI.xml

limiting AI offset knob

---

Engines/prop_75in2f.xml
Engines/prop_75in_2f_NACA_15-30deg.xml
Engines/prop_76in2f_NACA_15-25deg.xml
Engines/prop_76in2f_NACA_20deg.xml

Fixes #1341 
@dany93  I went ahead and created the PR fir this. If this is all we're doing then I guess it is ready to merge.

Add versioning to the propeller configuration files

---

Nasal/engine.nas

Fix typo in engine.nas concerning oil service hours increase

---

Nasal/engine.nas

Engine startup shaking effect (from c182s)

---

Tutorials/pattern.xml

Fix some typoes. Fix #1363

---

Nasal/c172p.nas
Systems/fuel.xml
Systems/views.xml

Fixes #1374
Fixes #1373
@legoboyvdlp Once merged these also need cherry picked into release 2020.3. I verified your first cherry pick it looks fine.
I'm tired of making issues for a simple bug fix so I am adding the fuel bug to this, this I changed the name. See the discussion at https://forum.flightgear.org/viewtopic.php?f=66&t=39392 if you have any questions as to why I changed it again. The PR you merged the other day technically fixe it but it didn't need all the superfluous code.
This is ready to go.

Bugs in view logic and fuel priority

---

c172p.xml

@legoboyvdlp would you mind double checking this. I stumbled on to this discrepancy and fixed it. If you approve you can merge it.

Equal amphibious gear spring coeff

---

Tutorials/altimeter.xml
Tutorials/engine-failure.xml
Tutorials/landing.xml
Tutorials/pattern.xml
Tutorials/preflight.xml
Tutorials/radios.xml
Tutorials/runup.xml
Tutorials/securing.xml
Tutorials/startup.xml
Tutorials/takeoff.xml
Tutorials/taxiing.xml

Remove airport-id from tutorials (Issue #1387)

---

Tutorials/amphibious-landing.xml
Tutorials/amphibious-night.xml
Tutorials/amphibious-takeoff.xml

Remove preset airport tag from tutorials

---

Models/Effects/interior/lm-interior-fuel-selector.eff
Models/Interior/Panel/c172p-panel/c172p.xml

Fixes #1394 
@legoboyvdlp if you don't mind, when you get a chance please review, merge and close. It's minor but I can't believe we never noticed.

Fuel selector objects pointing at wrong effect file

---

c172p-amphibious-set.xml
c172p-bush26-set.xml
c172p-bush36-set.xml
c172p-fg1000-kap-set.xml
c172p-float-set.xml
c172p-main.xml
c172p-set.xml
c172p-ski-set.xml

Annunciator panel is only used in a KAP140 equipped aircraft

---

Systems/fuel.xml
c172p-main.xml

Fix unusable fuel issue #1408

---

Nasal/c172p.nas
c172p-keyboard.xml

Amphibious gear keyboard bindings, formating

---

gui/dialogs/c172p-about.xml

Closes #1413 
@dany93 this is ready to merge after review.

Replace redirect URL

---

Nasal/avionics.nas
Nasal/electrical-fg1000.nas
Nasal/mooring.nas
c172p-fg1000-gfc-set.xml
c172p-fg1000-kap-set.xml
c172p-main.xml
gui/dialogs/aircraft-dialog.xml

Fixes #1437 
@dany93 
Please merge this last. It contains #1435 commits

Issue 1437

---

Systems/c172p-ground-effects.xml
Systems/ground-effects.xml

Refactor tiedown logic

---

Systems/systems.xml

Fixes #1447
@dany93 this is a documentation clarification change, it shouldn't affect anything performance wise.
I'm trying to test the value with and without the error for type=0. I am getting different results but don't know if it is related to the error value o something else.

Clarify alt static port configuration, change response time of interior static port

---

Models/Effects/pontoon/mooring.xml
Models/Effects/pontoon/mooringharness.xml
Nasal/interior-lighting.nas
Systems/c172p-ground-effects.xml
Systems/c172p-skis.xml
Systems/glass-rain.xml
Systems/yoke-cord.xml

Fixes #1449 
~Please wait to merge until copyright discussion is resolved.~

Wayne Bragg removing Wayne Bragg copyright in light of GPA license

---

Tutorials/takeoff.xml

Fixes #1454
@dany93
This is finished.

Reword step message in Takeoff tutorial

---

Models/Interior/Panel/Instruments/vor/vor.xml
Models/Interior/Panel/Instruments/vor/vor2.xml

Fix NAV needle deflections

---

c172p-main.xml

See http://wiki.flightgear.org/Aircraft-set.xml#Performance_and_Flight-planning

Added ICAO and performance data to <aircraft>

---

Models/Interior/Panel/Instruments/tc/tc.xml
Nasal/electrical-fg1000.nas
Nasal/electrical.nas
Systems/electrical-fg1000.xml
Systems/electrical.xml
c172-sound.xml
c172p-fg1000-gfc-set.xml
c172p-fg1000-kap-set.xml
c172p-main.xml

Issue 1495 elec sys bugs

---

c172p-set.xml

Fixes #1503 
This is long overdue and is ready to merged by anyone with access.

Add a fallback model index

---

Nasal/electrical.nas

Fix bug with ADF power switch shutting off also DME
Fix #1507

Fix issue 1507 / ADF power switch shutting off DME

---

README.md

Add contributor to list.
@hbeni does this work for you? I used both hbeni/benih beings you use both?

Add hbeni to contributor list

---

c172p-main.xml

Edit in sim contributor list, add benih, correct format of Jarl Arntzen

Cleanup contributor list

---

Models/Interior/Panel/Instruments/mag-compass/mag-compass-fg1000.xml
Models/Interior/Panel/Instruments/mag-compass/mag-compass-float-fg1000.xml
Models/Interior/Panel/Instruments/mag-compass/mag-compass-float.xml
Models/Interior/Panel/Instruments/mag-compass/mag-compass.xml
Systems/instruments.xml

Switched compass pitch/roll to damped c++ values

---

c172p.xml

See:
- Forums post from Davod Megginson: https://forum.flightgear.org/viewtopic.php?f=49&t=42055
- JSBSim discussion: https://github.com/JSBSim-Team/jsbsim/issues/1037

Adjust mixture setting to be able to go over-rich

---

c172p-main.xml
c172p.xml
gui/dialogs/aircraft-dialog.xml

Adds the option to adjust needed control forces (on joystick) by dynamic pressure

Modeling STICK-FORCE-PER-'g' and the effect of dynamic pressure on flight controls

---

Models/Interior/control-lock/control-lock.xml
c172p.xml

Replaces [c172p-team:Issue-1471](https://github.com/c172p-team/c172p/tree/Issue-1471) from [hbeni:Issue-1471](https://github.com/hbeni/c172p/tree/Issue-1471) which was merged to the wrong branch.
@hbeni please verify this is correct and merge!

Cockpit flight controls react to trim settings

---

Nasal/avionics.nas
Nasal/c172p.nas
Nasal/display-props.nas
Nasal/engine.nas
Nasal/save.nas
Nasal/state-manager.nas
Systems/engine.xml
Systems/flight-recorder/components/engine.xml
c172p-main.xml
c172p.xml

c172p should not overwrite fgdata's controls.throttleAxis()

---

Nasal/avionics.nas
Nasal/c172p.nas
Nasal/engine.nas
Systems/engine.xml
Tutorials/altimeter.xml
Tutorials/amphibious-landing.xml
Tutorials/amphibious-night.xml
Tutorials/amphibious-takeoff.xml
Tutorials/engine-failure.xml
Tutorials/landing.xml
Tutorials/pattern.xml
Tutorials/preflight.xml
Tutorials/radios.xml
Tutorials/runup.xml
Tutorials/securing.xml
Tutorials/startup.xml
Tutorials/takeoff.xml
Tutorials/taxiing.xml

This finishes off issue 1524. Update tutorials and cleanup.

Cleanup, tutorials use controls/engines/engine[x]/throttle

---

Nasal/save.nas

Issue 1539

---

NEWS.md
c172p-main.xml

Version 2024.1

---

NEWS.md
c172p-main.xml

Start of new 2024.1.1 LTS development branch.

Version 2024.1-git

---

NEWS.md
c172p-main.xml

2024 1 2 release

---

Models/Interior/Yoke/yoke-fg1000.xml
Models/Interior/Yoke/yoke.xml

Unselect yokes when transparency setting is <0.05 and hidden
