c172-checklists.xml

checklist: Add "Flashing Beacon" to "Starting Engine" (fixes #2)

---

Nasal/electrical.nas

Should fix #103. Please do `git checkout bug-103` to test this locally before giving a :+1:.

Fix #103 by forcing initialization of lighting state properties

---

Models/c172p-detailed.xml
Systems/als-lights.xml
c172p-detailed-set.xml

Fixes #77 
I have wired the taxi light to the alternate ALS light, so you can have two ALS lights if you enable taxi and landing lights.

Only show ALS lights if in internal view and master is on

---

Nasal/physics.nas

Previously, the nose gear broke on a vigorously maintained braking.

increase threshold damage for the nose gear

---

gui/dialogs/aircraft-dialog.xml
gui/dialogs/c172p-menu.xml
gui/dialogs/immat.xml

Cleaned up the two XML files, formatting, and tabs+spaces mixture mess.
Aircraft Options:
* Reduced padding and code size
* Replaced the "----" lines with orange horizontal lines
Immatriculation / Registration:
* Renamed "Immatriculation" (is this French?) to "Registration"
* Replaced "OK" button with "Apply" and "Cancel" buttons

dialogs: Clean up "Aircraft Options" and "Registration"

---

Models/c172p-detailed.xml

Were counter-intuitive.
issue https://github.com/Juanvvc/c172p-detailed/issues/156#event-300990125

Mixture and Throttle levers control by scroll wheel, inversion

---

c172p-fdm-dany93.xml

Wing damage with over-speed or over-g's.
It had been inserted in the "original" FDM (via wlbragg commit) but the alternative FDM had been left as it was.
It gave unknown properties and crash of the simulator at launch with this alternative FDM.

Alternative FDM: damage/left wing, right-wing properties insertion

---

Systems/fuel.xml
c172p-detailed-set.xml
c172p-fdm-dany93.xml
c172p.xml

Float chamber added.
In a first time, on the original FDM only (c172p.xml) for testing.
I've given some explanations in this post
http://forum.flightgear.org/viewtopic.php?f=4&t=25157&start=1395#p242612
To quickly see and understand the effects:
Full throttle with parking brake.
See "Fuel and payload", and fiddle with the main tanks [0] and [1] levels, or close them one by one. Observe the Float chamber [2] level.
A g < 0 feature is implemented, which stops the engine in some seconds. Fly with some negative g's (pushing the yoke in a climb is enough) and look at the floating chamber level.
Any(?) Other properties can be inserted in fuel.xml (switch tests). Setting these properties by any other way can starve or quickly stop the engine, or prevent it from starting ("primer 3 times" linked …

Fuel management: Float chamber

---

c172-checklists.xml

This is not 100% accurate, as per the C172 operating handbook the fuel gauges are checked during the preflight check. However the complete preflight check is not included in the checklists, and the fuel gauge check is instead part of the "before starting engine" checklist, which makes sense in practice. So we need to move the battery master item a few lines higher to be able to see the fuel gauge values. 
In the handbook the battery is turned off afterwards to save the battery since the preflight takes a while, but turning it off here does not make sense, as you'll be starting the engine in a few moments anyway in the sim when you follow the list.

Battery master needs to be on to check fuel gauges

---

c172-checklists.xml

This was pointing at the oil temperature gauge, which is not what you need to look at after the engine starts, it takes longer to move towards green. Fixing to point the marker at oil pressure gauge and scaled it a bit larger as well so you can see the value without the marker blocking it.

Point to correct gauge

---

Nasal/c172p.nas

Fixes #149
I think the proper fix though is to make sure JSBSim doesn't listen to the `/controls/gear` properties instead of (not) manipulating them.
For example, if you apply parking brake and then break all your gear by crashing, then currently JSBSim will apply the parking brake because the `/controls/gear/brake-parking` was already true before the gears got broken. But this issue only happens with the parking brake, not the normal brakes, because those return to 0 eventually.

Do not apply brake if corresponding gear is damaged

---

Nasal/avionics.nas
Nasal/c172p.nas
Nasal/doors.nas
Nasal/electrical.nas
Nasal/engine.nas
Nasal/immat.nas

While leaving out the var keyword when introducing new identifiers is not an error it is not a good practice since the behaviour can change from creating a new local variable to overwriting visible one without any notice (e.g. if a later added global module happens to have the same name as the new variable). Using var always creates a new local (= present module or function) variable and will never overwrite a larger scoped visible one, should one exist.

Added missing var-keywords in the Nasal files.

---

Systems/bushkit.xml
c172p-detailed-set.xml

Don't add /payload/weight entries for weights that the user should not see or touch in the fuel and payload dialog.
Signed-off-by: Anders Gidenstam <anders@gidenstam.org>

Hid FDM internal weights from the fuel and payload dialog.

---

Systems/bushkit.xml
c172p.xml

Previously, left and right were in a single load in the FDM, and every kit appeared in "Fuel and Payload" dialog with cursors.
After AndersG changes, https://github.com/Juanvvc/c172p-detailed/pull/232#issue-83163224, subdivision becomes possible with no useless lines in "fuel and payload". Clean.

Subdivide left and right bushkits and floats weights

---

Nasal/physics.nas
c172p.xml

Connected to this issue https://github.com/Juanvvc/c172p-detailed/issues/134#issuecomment-107867029
Indeed, the nose gear is hard to break without breaking the others. 
For this nose gear, I had to set the breaking force at 1400 lbs because it reached 1392 lbs at the end of a strong braking with the 36" bushwheels (1350 lbs threshold is needed with the default wheels).
I have included the" tool" for printing the exerted forces because it can be useful elsewhere and by someone else (under comments, of course).
@tigert if you can see for the breaking threshold due to side force (15 kts crosswind landing, full load).
I have set it at 1500 lbs (Y-force).
500 lbs can be enough for a very good crosswind landing, but that's easy to reach 600 - 700 lbs only by rolling not very straight. 700 - …

Gear damage by the forces exerted on gears

---

Nasal/engine.nas

At "Autostart" the parking brake is OFF.
This popup message is useless and confusing.
**Unless it is used elsewhere** (where?)

Autostart: parking brake is OFF ==> deletion message 'release brakes'

---

Models/Interior/Panel/Instruments/kap140/KAP140TwoAxisAlt.xml
Nasal/avionics.nas
Nasal/electrical.nas
Nasal/light.nas
Systems/als-lights.xml

Fixes #103
Some (parts of) instruments do not make use of `/sim/model/material/instruments/factor` (but this is a separate issue):
Someone who can edit `<animation>` parts of XML files of the instruments should add `/sim/model/material/instruments/factor` to these files.

Make instrument lighting depend on master battery and circuit breaker

---

Systems/c172p-hydrodynamics.xml

Added yaw damping, enabled the water rudder and disabled squat. The last one seems to be the bobbing at rest culprit, it goes over 2ft up and down while floating near at rest. The computation of squat for these cases need to be revisited before it can be enabled again. It is currently not an important part of the hydrodynamics.

Updated JSBSim hydrodynamics

---

Models/Effects/pontoon/left-spray.xml
Models/Effects/pontoon/left-wake.xml
Models/Effects/pontoon/middle-wake.xml
Models/Effects/pontoon/right-spray.xml
Models/Effects/pontoon/right-wake.xml
Systems/c172p-hydrodynamics.xml
Systems/flight-recorder/components/effects.xml
Systems/gearAGL.xml
c172p-set.xml

I made a property rule, everything worked perfectly with it except over MP. All the generic params looked correct but there just wasn't any wake. So I decided to do it with all the aliases. However as it turns out it was only going to save one alias because I needed groundspeed_kt separate anyway or I would have had to make a bunch of different prop rules and an alias for each which put us right back to where we were anyway. Look at the wake, spray, middle files, they all take different  groundspeed_kt params so it needed to be stand alone. That only left hydro/active-norm and ground/solid of which I also tried a prop rule fro the two. Again, locally everything worked fine, but not over MP. So we didn't save "one" alias. We can try to refactor later, maybe something will stand out that is …

MP wake effects

---

Models/c172p.xml

Fix showing "Transponder" label without requiring Ctrl+c

---

Tutorials/engine-failure.xml

Best glide speed for C172P according to Pilot Operating Handbook is 65 knots. Updated all the speeds to the tutorial.

Corrected best glide speed for C172P

---

c172p.xml

It is now possible to land on a concrete runway without nosing over as
the FAA seaplane operations handbook indicates should be possible without
severe damage. There is currently no damage modelled for this float
maltreatement but it could be modelled by increasing the float leak rate.
Signed-off-by: Anders Gidenstam <anders@gidenstam.org>

Tuned the friction of the float contact points.

---

c172-help.xml
c172p-keyboard.xml

Fixes #338. See PR #340 for the buggyness of the P key binding.
The panel does not show itself if /sim/current-view/heading-offset-deg
is not 0. Therefore, add an additional <binding> to set it to 0.
You only need to press P, there is no need to press c. First time you press P you need to wait a little because FlightGear needs to load the panel.

Set heading offset to 0 when toggling panel

---

Models/c172p.xml
Systems/flight-recorder/components/gear-amphibious.xml
Systems/flight-recorder/components/systems-instruments.xml
Systems/ground-effects.xml
c172-sound.xml

Fixes #349 
* Toggle `/controls/gear/water-rudder` in Internal Properties window to lower/raise water rudder.
* Start engine and press Ctrl + u to test stall horn.

flight recorder: Add rollspeed-ms of gear, water rudder, and stall horn

---

Models/Interior/Panel/Instruments/tc/tc.xml

Fixes #146 in ALS and Rembrandt.

Remove usage of model-transparent effect in TC to avoid weird colors

---

Models/Interior/Panel/Instruments/mag-compass/mag-compass.xml

There was discussion in #313 and #316 that seemed to reach the conclusion
that this 'helpful' display is not used. It is...
In fact it should be used on each start-up, and perhaps during flight to
set and keep the gyroscopic compass 'accurate'...
Tried to read through the history of this change...
wkitty42 commented 16 days ago #313
https://github.com/Juanvvc/c172p-detailed/issues/313#issuecomment-113345108
mag-compass - why is it `clickable`? Because we need the tool tip to tell us what it is on!
Yes, you can not change anything - it is a magnetic compass - but without zooming in, and repositioning to read it is difficult to read, as it is in RL ;=))
And some of us fly **without** the hud ;=)))) so need that tooltip. And was very amused that others consider the magnetic compass as an …

Re-add tooltip to magnetic compass.

---

Models/c172p.xml

@onox, I did this in hurry without a lot of thought .It appears to work but I don't know what all was done with recorder and MP in regards to the refactoring of the damage conditions. I think what happened was a prop for damage was removed and instead the props wing_??_damaged (floats) were incorporated.
But the (< 1 and > 0) for damage was never added to the damage condition.
You may want to write it differently than what i used. Like I said I wasn't really considering everything because I didn't make these changes and don't know what all was done. But I wanted to verify that this condition was all that got broke and I think it was.

Add strobe condition for  > 0 and < 1

---

Systems/engine.xml

I found a fix for the bug #354 , but it's probably not very elegant (though it works!). The thing is that the throttle displayed on the HUD is always from property `/controls/engines/engine[0]/throttle`, but the 180 HP engine currently controls only `/controls/engines/engine[1]/throttle`. If we set it to control the throttles of both `engine[1]` and `engine[0]`, then the HUD display shows the correct throttle position and the engine also behave normally (as changing `engine[0]`'s throttle rightfully does nothing to the 180 HP). 
@onox please feel free to decline this fix if you think it's too much of a hack, okay?

180 HP controls the throttle of both engine[1] and engine[0] properties

---

Models/c172p.xml
Nasal/c172p.nas
Systems/pax.xml
c172p-set.xml
c172p-views.xml

Creates a Cockpit Right Seat View. For this to work well, I also made the pilot model dependent of its weight (so that one can set 100 pounds of weight to the right seat and less than 100 pounds to the left seat and have an empty pilot chair). 
Fixes #416.

co-pilot view, pilot model now depends on weight

---

c172p.xml

Z-contact by the tail skid in the FDM was too low (z=8), which made it "touch" the ground prematurely (see external view by rolling at very high pitch-up angle). 
More importantly, it prevented from reaching a high pitch-up angle at landing (slow speed when grazing the ground, down to stall).
By changing for z=15 ==> Accordance between FDM and 3D view contacts, and very soft touching down at slower speed, higher AoA becomes possible at landing by progressively pulling the yoke so to pitch up and hold the plane.

Tail skid contact height

---

Systems/views.xml
c172p-mice.xml
c172p-set.xml

Fixes #476 
It works nicely with the external Helicopter View, Model View, and Walker Orbit View. Chase View gave weird results (distance as well as altitude of camera changes), so disabled it for that view.

Use mouse scroll wheel to zoom in and out for 'lookat' views

---

Nasal/avionics.nas
Nasal/c172p.nas
Systems/flight-recorder/components/switches.xml
Systems/ground-effects.xml

May fix #517 
@gilbertohasnofb Ask someguy if he can confirm. I'm assuming joystick code calls `controls.applyParkingBrake(1);` to toggle it. Both our function and the function we have overridden (`applyParkingBrake`) have one parameter that needs to be positive, but is otherwise unused.

Fix controls.applyParkingBrake

---

Models/c172p.xml
Nasal/c172p.nas
Nasal/engine.nas
Nasal/ki266.nas
Nasal/kma20.nas
Nasal/kr87.nas
Nasal/liveries.nas
Nasal/physics.nas
Nasal/tanks.nas
Nasal/weather.nas
c172p-set.xml
gui/dialogs/c172p-baggage-weight.xml
gui/dialogs/c172p-left-fuel-sample.xml
gui/dialogs/c172p-left-fuel.xml
gui/dialogs/c172p-oil-160.xml
gui/dialogs/c172p-oil-180.xml
gui/dialogs/c172p-right-fuel-sample.xml
gui/dialogs/c172p-right-fuel.xml

- all dialogs that are opened via pick animations (oil quantity, baggage weight, both fuel tanks and fuel sumps) are disabled if the aircraft is in movement
- added warning message when dialogs are disabled (as not to baffle people of why they can't click anywhere)
- fixed some indentation
- parking brake default state set to ON
- autostart sets parking brake automatically to OFF and also removes chocks, tie-downs and pitot tube cover, sets oil-level to a good value and removes any contamination from both fuel tank
Closes #543 and #548

Some improvements to the dialogs and autostart

---

Models/c172p.xml

Fixes #579 
~~~xml
<animation>
<type>select</type>
<object-name>RightWheelBKs</object-name>
<condition>
<and>
<not>
<property alias="/params/gear_right_broken/property"/>
</not>
<equals>
<property alias="/params/bushkit/property"/>
<value>1</value>
</equals>
</and>
</condition>
</animation>
~~~
Somehow it got set to 2.

Fix damaged 26" wheel from not displaying.

---

Systems/bushkit.xml

Fixes #593 
1. Start near the sea and switch to amphibian or sea plane
2. Get in the air and smash the aircraft to the ground near the water
3. Check that one or both of the pontoons are damaged or broken
4. Press Ctrl+u to get in the air and land on the water
5. You should see the damaged/broken pontoon start sinking a bit
6. Now click the "Repair" button. The leakage should disappear and the pontoon should fully float again.
@andgi To answer your question (in `Systems/bushkit.xml`): to reset a pid's integrator, you set its trigger to a negative value. In this case I used -1 as long as a pontoon is undamaged.

Bug 593: Reset pontoon leakage to 0 when undamaged

---

Systems/c172p-engine.xml

Higher RPM drop when using carb heat. Now at full power the drop is around 100 RPM.
Fixes https://github.com/Juanvvc/c172p-detailed/issues/609

Higher RPM drop when using carb heat

---

Models/c172p.xml
Nasal/c172p.nas
Nasal/engine.nas
Nasal/physics.nas
Systems/engine.xml
Systems/flight-recorder/components/engine.xml
c172p-set.xml

Fixes #608 
Not all calls to `killengine()` can be removed (read: moved to XML) because some depend on the altitude at the moment a wing gets damaged.
In `Nasal/engine.nas` I kill the engine temporarily for 0.25 seconds when oil level is low. I have also increased the maximum random duration from 3 to 10 seconds. 3 would give too much coughing.

Bug 608: Kill engine if propeller is broken

---

Systems/flight-recorder/components/engine.xml

Exiting the replay mode while aircraft was damaged during replay would not restore the crash state of the engine.
How to reproduce:
1. Crash into the ground to crash (kill) the engine
2. Repair the aircraft (propeller should be OK again)
3. Go to replay mode and let the aircraft crash itself
4. While the propeller is damaged, exit the replay mode
Without the fix the propeller would stay damaged, but with the fix it should be OK again (because you repaired the aircraft before entering replay mode).

Bug 608: Prevent Nasal from undoing repairing crashed engine

---

Models/c172p.xml

Fixes #613 
Scrolling up moves the air vents away from you, closing them. Dragging should still be the same: in the direction of where you want to move the air vent to.
I have also reduced the increment/decrement step from 10 % to 5 %. Did the same for the cabin heat and air knobs. The tooltips sometimes show a value that is off-by-one (for example, 44 instead of 45). That's something that should be fixed in flightgear/simgear.

Bug 613: Mouse wheel direction of overhead air vents is inverted

---

Models/c172p.ac

I see these never got corrected so here is the fix for it. Also there is a couple objects that are not being used for anything leftwindow_int and rightwindow_int.
I also just added a commit correcting a material error that crept in from somewhere.

Turn on TaxiLightCone and LandingLightCone objects.

---

Nasal/c172p.nas
Nasal/engine.nas
c172p-keyboard.xml
c172p-set.xml

Fixes #666 
This PR changes the behavior of "Autostart": when clicking on it, the tiedowns, chocks, and pitot tube cover are no longer removed. The reasoning is that they are only visible if the user has chosen to enable "Allow securing aircraft", and having that option enabled indicates that the user wants these things.
This change is debatable and I can revert it if too many people disagree.

Bug 666: Set heading offset when clicking on "Autostart"

---

WebPanel/ADF.json
WebPanel/c172p-webpanel-properties.json

This animates the compass-card of the ADF gauge. It is not automatically rotated, nor does it affect the needle in any way (like the VOR radial dial does) but it still has a knob that can be rotated to your current course, for example.

animate adf compass card

---

Models/Interior/Panel/Instruments/asi/asi.xml
Systems/indicated-airspeed.xml
c172p.xml

Conversion from Calibrated airspeed (previously: indicated on the instrument) to Indicated airspeed  taking into account the aerodynamics and instrumental errors. According to the C172P 1982 POH, page 5.9 (PDF 85/357).
About issue https://github.com/Juanvvc/c172p-detailed/issues/676.

Calibrated airspeed --> indicated airspeed conversion

---

c172p.xml

Straight backwards propwash effect was already implemented for the 160 hp version, but it had been forgotten when adding the 180 hp engine.
**To check it in the simulator (stopped on the ground with no or negligible wind):**
- 180hp
- parking brake ON
- Full or enough RPM
- Pull the yoke (elevator up) ==> the nose pitches up (the tail goes down due to propwash)
Not so easy for the effect on the rudder.
Checking it in the Internal properties:
- `fdm/jsbsim/aero/coefficient/Cmde` (Pitch_moment_due_to_elevator_deflection)
- `fdm/jsbsim/aero/coefficient/Cndr` (Yaw_moment_due_to_rudder)
_(among other effects, can be used to relieve the strain on the nose wheel when rolling on a bad ground)_

FDM: add (straight backwards) propwash effect for 180 hp version

---

Systems/indicated-airspeed.xml

Fixes #723 
`/fdm/jsbsim/velocities/vc-kts` does not react to failure of the pitot
system. Use `/instrumentation/airspeed-indicator/indicated-speed-kt` which
does depend on the pitot system. Note that the indicated airspeed system
assumes a perfect pitot, thus it practically is a calibrated airspeed
indicator.
There's a small difference between `vc-kts` and `indicated-speed-kt` (see https://github.com/Juanvvc/c172p-detailed/issues/723#issuecomment-191188420) but it is quite small (< 1 kt usually).

Bug 723: Use indicated-speed-kt which uses an almost perfect pitot, but can fail

---

Models/c172p.xml

Torsten moved the file marker.xml in FGDATA from `Models/Aircraft` to `Aircraft/Generic`, and so we must update our reference to it.
Fixes https://github.com/Juanvvc/c172p-detailed/issues/733

updating marker.xml path

---

Models/c172p.xml
gui/dialogs/c172p-oil-160.xml
gui/dialogs/c172p-oil-180.xml

Better conditional for oil dialogs. 
Closes https://github.com/Juanvvc/c172p-detailed/issues/743
And although discussed in that issue, I have not implemented the same conditionals for the securing objects. I attempted to do so, but the result was buggy and I couldn't narrow down the problems. Also, it looked quite inelegant to add the message "you can't add/remove tiedowns/chocks/pitot tube cover with the engine on" + the conditional to 12 hotspots in the Models.xml (that is, 6 for the tiedowns, 2 for each type of chocks and 2 for the pitot tube cover). I am not sure it's worth all this trouble since they are working just fine as of now (with groundspeed < 1.0). But in case you guys think it's worth to implement this, then do not merge this PR yet and let's discuss how to do it further.

better conditional for oil dialog

---

Nasal/c172p.nas
Nasal/engine.nas
c172p-set.xml
gui/dialogs/aircraft-dialog.xml
gui/dialogs/c172p-left-fuel.xml
gui/dialogs/c172p-right-fuel.xml

Closes #757 
- better autostart function: sets oil level to max, sets fuel to 25% for each tank if any of them is lower than 25% (min recommended for safely operating the 172), automatically crank and starts the engine
- removed the "complex engine" option from dialogs
- small fix to fuel dialogs: the max level was wrongly set to be 28 gal instead of 21.5 gal
- in the `c172p-set.xml` file, the nasal file `c172p.nas` is declared before all others so that in the future any of its functions may be called from the ones below

Bug 757: better Autostart function

---

Tutorials/runup.xml
Tutorials/takeoff.xml
Tutorials/taxiing.xml

Add securing=false to runup, takeoff, and taxiing tutorial.

---

Models/c172p.xml

Closes: https://github.com/Juanvvc/c172p-detailed/issues/795
When pressing Ctrl+C, external hotspots do not show if they are hidden by the fuselage, but if you click in the correct position they do work (e.g. it's possible to open the oil dialog or add/remove chocks to the front wheel from the pilot's view).
This PR adds conditional for these so that they are only clickable if the view is external.

Bug 795: External hotspots not clickable from cockpit any longer

---

Nasal/c172p.nas
Nasal/engine.nas
c172p-set.xml
c172p.xml

Closes #791 
This function should work better than before, and it should start the plane even at low pressure environments. If the autostart function does not succeed in starting the engine within 5 seconds, it will give up and show an error message. This will happen at very high and very low pressure airfields, and the user is then instructed to manually start the engine.

Improving autostart function

---

Models/c172p.xml
gui/dialogs/aircraft-dialog.xml

Closes #807 
This PR changes the primer tooltip, so that hovering above the primer shows how many strokes have been made so far. Also, the primer is reset now when the engine or landing gear configuration changes.

Primer tooltip

---

gui/dialogs/aircraft-dialog.xml

Closes #814 
Repair and Recharge Battery buttons in the Aircraft Menu should now work when the aircraft has crashed

fixing issue with buttons

---

Models/Interior/Panel/Instruments/kt76a/kt76a.xml
Models/Interior/Panel/Instruments/kx165/kx165-1.xml
Models/Interior/Panel/Instruments/kx165/kx165-2.xml
Systems/als-lights.xml

Closes #770 
This PR does the following:
- makes the digits of both COMMs and NAVs digital displays less bright, so they look more similar to the AP, DME and ADF
- uses better conditionals for the radiance effect by the COMMS, NAVs and ADF radios: before if the radio illumination was set to 0%, there was no radiance effect even though that's the position in which the displays are at maximum intensity (daylight mode). So now they take that into consideration
- the conditional also removes a `<product>` from `<expression>` which was making the radiance effect appear in an exponential factor that looks bad and made no sense to me
- better colour for transponder ident and ident button backlight, makes them look more similar to the orange hue of the other digits (as opposed to the dark full …

Illumination intensity and radiance effect on/by radio stack

---

Models/Interior/Panel/Instruments/kr87-adf/kr87.xml

Closes #401 
Now ADF frequency knobs (inner and outer) as well as the swap frequency button work while the sim is paused

Kr87 knob now works while the sim is paused

---

Models/Interior/Panel/Instruments/kx165/kx165-1.xml
Models/Interior/Panel/Instruments/kx165/kx165-2.xml

Closes #819 
Setting full rotation to vol knobs of kx165, see issue above for more details. This is the new position for full volume (100%):

Setting full rotation to vol knobs of kx165

---

Models/Interior/Panel/Instruments/EGT/EGT.xml
Models/Interior/Panel/Instruments/kr87-adf/ki227_228.xml
Models/Interior/Panel/Instruments/kr87-adf/kr87.xml
Models/c172p.xml

Fixes #30
Most instruments can be hidden at range higher than 25 meter. The radio stack is hidden beyond 60 meter because it shows a distinguishable gray background.

Bug 30: Hide most instruments further than 25 m and radio stack 60 m

---

gui/dialogs/aircraft-dialog.xml

Closes #827 
When changing between the 160 HP and 180 HP engines, the user would get the following error:
`Failed to execute command dialog-close`
This is because of how the oil dialogs was handled. See the issue above for the explanation of what caused it and how this fix work

Fixing console error message when changing engines

---

c172-sound.xml

Closes #776
It turned out I had to lower the offset of the engine sounds quite a bit now, since opening the windows and doors raise the volume and it starts clipping again. I also tried to activate all other sounds of our plane (repair, crash, doors, knobs, switches, etc.) and I tested all of them with both doors and windows opened, and it looks like there are no more clipping issues. I suggest whomever test this to do the same (remember to use ` --log-level=debug` when testing).
Also, given that the engine sounds were lowered a bit, we might have to consider doing the same for the other sounds of our plane. That said, it all sounded fine to me, so I am fine with merging this as it is.

lowering engine sound offsets

---

Nasal/c172p.nas
Nasal/engine.nas
Systems/engine.xml
c172p-set.xml
gui/dialogs/aircraft-dialog.xml

Fixes #360 
A first attempt to model carburetor icing and carburetor heat. Before merging, please test _extensively_ to make sure this doesn't break anything. Also, I think we should keep issue 360 opened since both @onox and I agree that this implementation here isn't really the best approach.
For testing: first of all, go to the aircraft menu and enable carb icing.
Then play with the weather:  go to the weather menu, select High Pressure scenario but do not apply, then select Manual and play around with the values `20/08` in the METAR string, the first being the temp in Celsius the second being the dew point in Celsius. The closer they are the more humidity there is in the air. Then compare with the chart below (in Fahrenheit!):
The accumulation of ice is given by the property …

carburetor icing and carburetor heat 

---

Nasal/c172p.nas
Nasal/electrical.nas

Closes #838 
This PR makes changes to the autostart function:
- it now handles battery charge and circuit breakers locally instead of calling a function from electrical.nas. The issue was that when the option of starting the sim with engines on was toggled, the autostart function was being called before the electrical system was initialized. I did not manage to force it to initialize before the c172p.nas, but on top of that doing so could have caused more bugs. Doing things locally looks far more elegant in my opinion (though the original battery recharging function should stay there as it's used by one of the GUI dialogs)
- changed the order of some lines in the autostart function to make it more logical to a reader. E.g. checking for fuel level and battery charge is now done before …

Autostart handles battery charge locally

---

Systems/bushkit.xml
c172p.xml

Closes #847 
- fix empty aircraft weights, as POH values include full oil tank (see issue above for full discussion)
- removes old comment about starting the 180hp engine; this comment does not seem to be actual any longer

Fixing weights

---

Nasal/engine.nas
Systems/bushkit.xml
Systems/c172p-engine.xml
c172p-set.xml
c172p.xml
gui/dialogs/aircraft-dialog.xml

See https://github.com/Juanvvc/c172p-detailed/issues/851#issue-186835178
- Changes the way aircraft weight and CG are calculated, by _subtracting_ the _consumed_ oil from the POH Basic Empty Weight. Much more simple to understand and easier to calculate and implement.
- Fixes some bugs about the oil content (7 or 8 quarts) vs the 160 hp / 180 hp engine.

Consumed oil weight and a few bug fixes on full oil vs the engine.

---

Nasal/engine.nas
c172p-set.xml
gui/dialogs/aircraft-dialog.xml

Correction: set "oil-lacking" = 0 when "Allow oil management" is **disabled** (unchecked).
(only "oil-consumed" was reset to 0 and "full level" reset to 7 or 8)

if Oil management disabled, set oil-lacking = 0

---

Systems/bushkit.xml
c172p.xml

The initial value (already in the jan. 2012 FG version) was 1500 lbs in the FDM.
According to the **Cessna 172P Skyhawk 1982 (160hp) POH p.6-10 (112/357 pdf)** the basic empty weight (= with full oil) is **1467 lbs**.
The empty center of gravity has been recalculated, to be in accordance with this same POH (57300 lbs.ins, which gives **39.1 "**).
Probably not very noticeable on the behaviour but at least for the consistency...
The 180 hp empty weight and CG are unchanged.
The extra weight added at 160 hp to obtain the 180 hp version has been also recalculated for that.

160 hp aircraft: empty weight correction, 1467 lbs in accordance with POH

---

Models/c172p.xml
Tutorials/preflight.xml
Tutorials/securing.xml

Fix #849 
The properties for pitot cover, tiedowns and chocks in the securing tutorial were outdated. I corrected them :smirk:

Fixing issue #849 and correcting the securing properties in securing.xml

---

Models/c172p.xml
c172-sound.xml

Closes #833
This PR does two things:
- delays the opening of the baggage dialog by 2 seconds when clicking on the baggage door, so that the animation is complete before the dialog is opened
- adjusts the timing of the sound of the baggage door while opening, it was too delayed

delay baggage dialog, better sound activation timing

---

Models/c172p.xml
Nasal/c172p.nas

Closes #861
This PR implements control surfaces check. In the external view or using the walker, simply click on the ailerons, rudder and elevator to move them as if the pilot was testing them. Animation only works if the engine is not running and if the groundspeed is < 1.0 knots (same condition as tie-downs, chocks, etc.). The animations last for only 1-2 seconds and will override any joystick input during that time. The aileron animation temporarily disable auto-coordination if that's on, so that the ailerons move alone without moving the rudder.
Here is a video of this work (note that the video was done before the auto-coordination toggling I mentioned above):
https://youtu.be/ieVGiAv0ntI

implementing control surfaces check

---

Models/Interior/Panel/Instruments/kr87-adf/kr87.xml

Solves #885 
Basically, I broke that display in the commit https://github.com/c172p-team/c172p-detailed/commit/5bb4bb618a9467cc720a2fc7adb582a11c49fc8e
I am creating this PR rather than reverting it because 1) @onox has made other modifications to this same file after that commit and 2) I also had removed some unnecessary lines of code in that fateful commit, so this had to be done manually. Please see the issue description for more information.

Fixing display of the ADF timer

---

Nasal/c172p.nas
Nasal/engine.nas
Systems/engine.xml

The carburetor icing system has been reviewed and several things have been improved:
- adjusted ice accumulation rate in icing conditions
- no ice accumulation when the engine is not running
- adjusted effectiveness of carburetor heat, which now is related to the engine exhaust temperature
- engine temperature affects ice formation (the warmer the engine, the lower the icing rate)
- the engine now coughs when the ice is melting, and the amount of coughing is proportional to the quantity of ice (i.e. severe icing accumulation == severe coughing)
- leaning when engine is coughing due to ice melting can help with coughing
- coughing can also happened due to fuel contamination with water, and the coughing interval is also proportional to the quantity of water
- lowered limit of critical oil …

Carburettor icing and other engine related improvements

---

Nasal/c172p.nas
Nasal/engine.nas

Fixes #909 
`fdm/jsbsim/propulsion/engine[n]/volumetric-efficiency` should be `0.85` for either engine, not `1.0`. A filter introduced by the carburettor system was overwriting that value into `1.0`, thus making the engine more powerful than it should. The following PR fixes this by correcting the input property of that filter, which is generated in the carburettor icing Nasal implementation.
For more discussion on this, please see the issue above.

volumetric efficiency should be 0.85 and not 1.0

---

Nasal/engine.nas

Closes #916 
Now starting the sim with complex engine procedures set to `false` will not break the oil temp and pressure gauges. For testing purposes: if complex engine procedures is set to `true`, then toggle it to `false` and _restart  the sim_ to confirm everything works as fine, as the bug was present only when starting the sim with this property set to `false`)

fixing oil temp and pressure gauges when complex procedures is false

---

Engines/eng_io320.xml
Engines/eng_io360.xml

Fixes #918 
**Necessitates a very recent FG version** (git 072bad4f50 from 27 April 2017) in which the oil pressure constants can be configured from the engine config file.

Engine: Oil pressure at start, pressure vs RPM

---

Systems/c172p-damage.xml
c172p-set.xml

I changed a few lines (logic criteria) in the wing damage conditions. Unless I didn't understand the initial logic behind, I thought that some conditions seemed inappropriate.
I think so but I hope that it works as expected, because checking the over-g values in flight is rather hard. Moreover there are many possibilities / combinations (velocities, g-overload, roll moment).
No fundamental change, only (I hope) a refinement.

wing damage conditions, minor changes

---

Nasal/engine.nas

2018.1 introduces new "all" properties for throttle, mixture and prop pitch this is the correct way[1] to interface with the axis based controls - use a listener on the -all properties as below. This will retain compatibility with previous versions of FG and 2018.1.
* /controls/engines/throttle-all
* /controls/engines/mixture-all
-------------
[1] The controls.throttleAxis, mixtureAxis, propellerAxis bindings should no longer be overridden directly - simply because the way they use cmdarg() makes it impossible to change the interface inside controls.nas

Fix engine axis bindings for 2018.1 compatibility.

---

Models/Interior/FE-ELT/fe2.xml

Fixes #976 
Prevents FG printing `Could not find at least one of the following objects for animation: 'extinguisher2'` to the console. Interior effect should be applied again.

Bug 976: Fix applying effect to renamed object 'extinguisher'

---

c172p.xml

Hi there,
I added a feature to FlightGear v2017.3.1 that allows aerodynamic interaction between the aircraft and AI models. The feature is briefly described in a [dedicated article](http://wiki.flightgear.org/AI_wake_turbulence) in the FlightGear wiki.
All you need is to add external reactions that models the induced aerodynamics loads on the aircraft. The resultant force and moment will superpose to the rest of the forces and moments computed by the FDM.
The computations made by FlightGear assume that the force is located at the intersection between the main wing leading edge and the aircraft plane of symmetry. This is important for the resulting moment to be correctly computed. I tried to estimate that position for the c172p at x=-4.7in and z=50in but this might not be quite accurate. …

Add force and moment induced by AI wakes.

---

c172p-keyboard.xml

I don't know if this change is acceptable upstream or useful to other people, but it has been very useful to me in night flights.

Add keyboard shortcut for the flashlight

---

c172p-set.xml
c172p.xml

Fixes #985 
* Fix wrong production year in `c172p-set.xml`
* Removed the word `detailed` from the description in `c172p-set.xml` as this has become the de-facto default aircraft and not a separate "detailed" model which would need to be differentiated
* Improves description in `c172p.xml`, as `Cessna 172P Skyhawk` is better than `Cessna C-172`

Fix wrong production year in xml files

---

Models/Interior/Panel/Instruments/VSI/VSI.xml
c172p-set.xml

This fixes the needle not pointing to the right numbers, and numbers the autopilots in the -set file.
Any questions just ask. This *does not* include my AP rework since that is not ready yet.
Kind Regards,
Josh

Fix VSI interpolation to match texture, number autopilots in -set

---

c172-sound.xml

Fixes #1015 
Fixes #959 
* gyro sound now decreases with distance, being barely audible from the outside views
* engine sound is louder at idle
* engine sound is a bit higher pitched
How to test it:
* test the gyro sound from several distances outside
* test that the gyro sound decreases in volume if you go to cockpit view and move the view outside
* test engine volume and pitch at idle
* test engine volume and pitch on the green arc
* test engine volume and pitch on a suicidal dive

Sound improvements

---

c172p-set.xml

With liberal use of rebasing and force pushing I managed to clean this up for you 😉 
Hope this is satisfactory.

Add default for /engines/active-engine/damage_allowed

---

gui/dialogs/aircraft-dialog.xml

Correct Astro Tech Digital Clock name in aircraft dialog

---

Models/Effects/interior/c172p-interior-radiance.eff
Models/Effects/interior/c172p-interior.eff
Models/Interior/Panel/Instruments/AI/AI.xml
Models/Interior/Panel/Instruments/BatteryGauge/BatteryGauge.xml
Models/Interior/Panel/Instruments/EGT/EGT.xml
Models/Interior/Panel/Instruments/FuelOilAmps/c172fuel.xml
Models/Interior/Panel/Instruments/FuelOilAmps/c172oil.xml
Models/Interior/Panel/Instruments/RPM/RPM.xml
Models/Interior/Panel/Instruments/VSI/VSI.xml
Models/Interior/Panel/Instruments/alt/alt.xml
Models/Interior/Panel/Instruments/asi/asi.xml
Models/Interior/Panel/Instruments/clock/clock.xml
Models/Interior/Panel/Instruments/digital-clock/digital-clock.xml
Models/Interior/Panel/Instruments/hi/hi.xml
Models/Interior/Panel/Instruments/hobbs/hobbs.xml
Models/Interior/Panel/Instruments/kr87-adf/ki227_228.xml
Models/Interior/Panel/Instruments/mag-compass/mag-compass-float.xml
Models/Interior/Panel/Instruments/mag-compass/mag-compass.xml
Models/Interior/Panel/Instruments/tc/tc.xml
Models/Interior/Panel/Instruments/vac/vac.xml
Models/Interior/Panel/Instruments/vor/vor.xml
Models/Interior/Panel/Instruments/vor/vor2.xml
Models/c172p.xml
Systems/als-lights.xml

Fixes #1192 
@onox 
This is the bare minimum so far. Shader set to lowest setting does not work, you have to have ALS off.
Do we also want this as a fallback for the shader setting?
I can try to integrate some ambient radiant light later on this evening too if we wan't. Without it it looks a bit dark as you can't see anything but the gauges.

Add integral lighting to panel instruments for default renderer

---

c172p-set.xml

Currently, the frequencies are set to `0` in the `-set.xml` file. I've changed them to the minimum value each can have:
`118.0` for COMMs
`108.0` for NAVs
`200` for ADF

setting initial frequencies

---

c172p-set.xml

@wlbragg What @wkitty42 wrote was right, those frequencies are saved in the autosave files in `~/.fgfs`, so to test this one needs to delete those and also the `c172p.xml` file from `aircraft-data`. After doing that the COMM and NAV frequencies were resetting correctly to 108.00 and 118.00 Mhz, but the ADF uses Khz and not Mhz. This commit fixes that and resets it to 200.0 as expected. Please test and merge this so that I can cherry pick it.

Initial frequencies

---

Models/c172p.xml
c172p-set.xml

Fixes #1210 
Visor rotations are allowing the visors to rotate out of bounds and through solid objects. This PR corrects that issue.
I have some confusion as to why this is happening and also the numbers don't seem accurate to me.
The rotation visually looks like it should be close to 180, it was at 140 but now needs to be at 90.

Limit visor rotations

---

Systems/c172p-engine.xml

Fixes #791
Simple change to autostart mixture at sea level to 1 VS .95 for full power.
This should be ready to merge after review.

Mixture set to 1 at sea level in autostart

---

Systems/glass-rain.xml

Fixes #1251 
This is ready to merge unless we want to increase the windspeed value even higher.

Increase wind speed required to drive rain animation over windshield

---

Systems/fuel.xml

JSBSim now allows to set a volume of unusable fuel below which fuel can longer be drained from a tank.
This feature has been added following the request in issue JSBSim-Team/jsbsim#141 from @legoboyvdlp. This also allows the PR #1249 to become functional.
This PR updates the fuel system of the c172p to account for the volume of unusable fuel.

Account for the volume of unusable fuel.

---

Systems/bushkit.xml
c172p-set.xml

Fixes #1267
This fixes a persistent data issue. When doing a seaport relocation it is necessary for the ``` fdm/jsbsim/bushkit ``` property ro be persistent.
The second part of the PR addressee the structure of a conditional originally looked to be wrong, but on closer examination it was technically correct. It was changed but incorrectly (by me, I forgot to change the order of the comparison). It is now changed again but the correct way. We could leave it like it was originally but it was a bit confusing. What I am not sure of is if the original way was necessary because of a little known issue of
``` var <  const ... var > const ```
needing to be written as
``` var < const ... const < var ```
I think I originally changed it (incorrectly because I forgot to flip the order) when I noticed …

Missing aircraft saved data, correct conditional

---

c172p-float-set.xml
c172p-set.xml

The fallback model (in fgdata) for the C172 is index 1; this allows use of the low detail option and avoids blue/yellow glider when the model is loading (over MP).
Also fixed an invalid XML definition; the xml tag refers to the xml version not the file version and must be 1.0

Added fallback model support

---

Systems/flight-recorder/components/effects.xml

Fixes #1212 
I'm doing this in the blind as I am unable to record tapes right now for some reason. It crashes my fg session when I hit save. I have tried a few different directories to no avail
If someone can test this and see if this ail all that is needed I would appreciate it.

Add altitude-agl-m signal to flight recorder

---

Models/c172p.xml
Systems/bushkit.xml

Fixes #1255 
This is finished, We load the GPS model once and use a translate animation to move it if the amphibious bushkit is selected.
The interior shadow when in amphibious mode is slightly off, but not enough to warrant major effort required to fix it, if it is even possible.
If @legoboyvdlp or @gilbertohasnofb can merge this after testing I will cherry pick it to the release branch.

Load GPS only once and translate instead

---

Systems/instruments.xml
Systems/mooring-pos.xml

Fixes #1286
Incidental - I didn't feel like creating a separate issue just to add a couple new mooring locations. I hope that isn't an issue for anyone.
If you all want to wait to merge this, I did a complete breaker and electrical system for the amphibious gear select, gear advisory and gear hydraulics for the pa18. I can add it to the c172p conditioned on the amphibious being selected.
Right now, in the c172p, I think it is simply tied into the master switch and alt breaker.

Issue 1286

---

Nasal/physics.nas

Fixes #1290 
I need to merge this and back port to our 2019.1 release immediately as I am holding up 2019.1 at remote.
I found this after one last test, after I merged the main issue https://github.com/c172p-team/c172p/pull/1289
Total apologies for doing this out of our normal procedures.

Amphibious gear switch not to trigger repair timer if pontoon damaged

---

Nasal/physics.nas
Systems/c172p-damage.xml

Fixes #1293 
Change repairing flag to a traversing flag. This allows for gear traversing without causing damage. Repairing flag is no longer used so it eliminates fixing of other damage on gear switch event.

Issue 1293

---

c172-help.xml
c172p-keyboard.xml

the in-sim aircraft help said 'f' was the toggle for the flashlight but only 'F' was defined in the keyboard bindings. this commit makes both keys valid as the flashlight toggle so we don't have to fumble about in the dark ;)

Wkitty42 flashlight patch 1

---

Models/c172p.xml
Nasal/c172p.nas
c172-sound.xml
c172p-set.xml
c172p.xml
gui/dialogs/aircraft-dialog.xml

Closes #1330
The idea behind this PR is:
* any lever that moves in/out or up/down will match the direction of the scroll
- scroll up: raise flaps
- scroll up: move throttle and mixture in
- scroll up: move trim wheel up, lowering the nose
* for knobs that turn on a different plane (e.g. all gauge knobs), scrolling up means increase of value, just like any GUI out there (e.g. volume knobs on OS's). This will also match other flight simulators as far as I know.
* I also slowed down the animation of the scroll wheel so that it looks more smooth, it was moving too much for each small step of trim and did not look too good.

Issue 1330

---

c172-help.xml
c172p-keyboard.xml
c172p-main.xml
c172p.xml

Adds standard aerotow capability
- Glider presses `CTRL+O` behind the plane to hook into the Cessna
- Cessna pilot can release hook anytime by pressing `SHIFT-O`
(Moved Domelight keybind `SHIFT-O` to `o`, as `SHIFT-O` is the default aerotow release)
After merging:
- add c172 to the [towing overview](https://wiki.flightgear.org/Howto:Do_aerotow_over_the_net)
- add `aircraft/Glider tug` to [C172P infobox template type](https://wiki.flightgear.org/w/index.php?title=Cessna_172P/info&action=edit)
- add a short section to the [C172P wiki page](https://wiki.flightgear.org/C172) that it can aerotow (example: [Cub](https://wiki.flightgear.org/Piper_J3_Cub#Aerotowing))
----
Tested with ASK21:
----
Fix #1361

Add aerotow support

---

Systems/fuel.xml

Fixes #1371 
@legoboyvdlp this fixes and issue where when in the "Allow Damage" mode and you crash (like nose and prop damage, front gear) the engine doesn't stop anymore. This fixes it. See the #1371 issue for explanation and if you know why the original logic doesn't work, please explain.
Anyway, this new logic does work and once merged needs to be cherry picked to 2020.3

Bug in fuel logic

---

Systems/views.xml
c172p-mice.xml

Fixes #1373
Adds back in the default mouse action when in a viewfrom view mode.
@Megaf 
Please pull and test this.
@legoboyvdlp after @Megaf tests and confirms this works, would you mind testing what you can as far as normal views you use and if satisfied, merge and cherry pick again to 2020.3.
Thanks

Allow default action in viewfrom in mouse manager

---

c172p-fg1000-gfc-set.xml
c172p-fg1000-kap-set.xml

As we have at https://wiki.flightgear.org/FG1000#Multikey_Support, the FG1000 should support multi-keys.

Add multi-key support for FG1000

---

Models/Interior/Panel/Instruments/kap140/KAP140TwoAxisAlt.xml

Fixing rather a typo so as the right value of hpa to be displayed when flying a c172p of release 2020.3

Fix hpa displayed values at KAP140 on c172p

---

Models/Interior/Panel/c172sp-panel/c172sp.xml
c172p-fg1000-gfc-set.xml
c172p-fg1000-kap-set.xml
c172p-main.xml

Fixes #1422 
@dany93 this is a fix for a couple issue on the fg1000 variants for nav and adf. The nav1 and nav2 radios had the wrong properties applied and a typo. It was causing the nav1 audio button on the audio panel to shut off the nav1 radio. The nav2 audio button also was incorrectly configured. The adf audio switch on the audio panel was also mis-configured. A couple properties initialized in the fg1000 variants were moved to the common or main file as they are used in all variants.
Without going into details I verified the following on the fg1000...
ADF audio works,
ADF radio sets ADF direction logic on the fg1000 PFD
NAV1 and NAV1 audio works and the audio panel NAV1 and NAV2 buttons no longer affect the fg1000 PFD NAV 1 and NAV2 logic adversely.
I'm confident this can be merged …

FG1000 audio panel and radio bug fixes

---

Nasal/electrical-fg1000.nas

Fixes #1421 
@dany93
I think I got it. It appears that it was a loading order timing issue. I changed the order of when the electrical loads and the fg1000 and I also set them to an fdm-initialized timer.
Feel free to merge this if it fixed the persistent data issue for you. I change the name of the issue and the PR as it pertains to the persistent data and not really anything to do with variant data.

Reorder electrical and fg1000 loading timing

---

Nasal/engine.nas
Systems/instruments.xml

Fixes #1424
@dany93 please test.
The only other thing I would like to verify is if we can delete the unused filter in Systems\instruments.xml. Starting at line 189.
~~~
<filter>
<name>Engine Total Hobbs Hours</name>
<type>gain</type>
<input>
<expression>
<div>
<sum>
<property>/sim/time/hobbs/engine[0]</property>
<property>/sim/time/hobbs/engine[1]</property>
</sum>
<value>3600.0</value>
</div>
</expression>
</input>
<output>
<property>/instrumentation/clock/hobbs-meter-hours</property>
</output>
</filter>
~~~
If is is indeed not being used anywhere I want to delete it before merging.
@wkitty42 maybe you can help verify it is not being used anywhere?

Track engine hours per engine

---

Tutorials/preflight.xml
Tutorials/securing.xml
Tutorials/startup.xml

A couple of tutorial fixes. They weren't getting past the parking brake being set due to stale reference to /sim/model/c172p/brake-parking, nor the circuit breakers due to a stale reference to the aircond circuit breaker.

Tutorial fixes

---

Models/Interior/Panel/Instruments/mag-compass/mag-compass-fg1000.xml
Models/Interior/Panel/Instruments/mag-compass/mag-compass-float-fg1000.xml
Models/Interior/Panel/Instruments/mag-compass/mag-compass-float.xml
Models/Interior/Panel/Instruments/mag-compass/mag-compass.xml
Nasal/electrical-fg1000.nas
Nasal/electrical.nas
Systems/instrumentation.xml
Systems/instruments.xml
c172p-amphibious-set.xml
c172p-bush26-set.xml
c172p-bush36-set.xml
c172p-fg1000-gfc-set.xml
c172p-fg1000-kap-set.xml
c172p-float-set.xml
c172p-set.xml
c172p-ski-set.xml

Magnetic Compass enhanced
- simulated pivot mount
- can get stuck when outside the pivots pitch limits
- avionics have electrical influence on the bearing (compass correction is the same as it was before with all avionics on; by coincidence its the same)
(Ported over from the c182s)

Magnetic Compass enhancements

---

Models/Interior/Panel/Instruments/hi/hi.xml
Models/Interior/Panel/Instruments/mag-compass/mag-compass.xml

Currently the tooltips of the HI knobs and the magnetic compass show the heading values `floor`ed.
This PR makes them show rounded values.
Old:  `123.95` => `123`
New: `123.95` => `124`

Show rounded headings in tooltips (Mag. Compass, HI)

---

Models/Interior/Panel/Instruments/mag-compass/mag-compass-fg1000.xml
Models/Interior/Panel/Instruments/mag-compass/mag-compass-float-fg1000.xml
Models/Interior/Panel/Instruments/mag-compass/mag-compass-float.xml
Models/Interior/Panel/Instruments/mag-compass/mag-compass.xml

Clamp the compass pitch and roll animation to sane values.
This is needed in case someone disables the roll/pitch stuck limits.

Magnetic Compass: Clamp roll/pitch animation

---

Models/Interior/Panel/Instruments/kap140/nav-selector.xml

This re-applies [the fix from fgdata](https://sourceforge.net/p/flightgear/fgdata/ci/b1f87ac535ed7180d8ea4307882541e56862188e/) that was lost when the Github was synced to fgdata. By pushing the fix to the source repo at GitHub, it will be fixed again in fgdata upon the next sync.
For details, see https://sourceforge.net/p/flightgear/codetickets/2680/

Fix autopilot DigitalFilter: unknown config node: value

---

Models/Interior/Yoke/yoke-fg1000.xml
Models/Interior/Yoke/yoke.xml
Nasal/c172p.nas
c172p-main.xml
gui/dialogs/aircraft-dialog.xml

Added yoke transparency.
Yoke is not hidden completely anymore, but made transparent, so pilot can still see the yoke while being able to see instruments behind it.
Transparency setting is stored between sessions.
For more Details also see: https://github.com/HHS81/c182s/pull/392

Add transpaent yoke hiding

---

Models/Exterior/towbar/towbar.xml

This helps with a small bug with quick clicks not "gripping". Handling does not make a difference.

Towbar: Release force instantly instead of "slow" decay

---

c172p-main.xml

This adds compatibility to the landing_rate_addon https://github.com/RenanMsV/landing_rate
See also C182 sister ticket: https://github.com/HHS81/c182s/issues/562

Add default props/values for vertical-speed-indicator

---

Models/c172p.xml
Nasal/interior-lighting.nas
Tutorials/amphibious-night.xml
c172p-keyboard.xml
gui/dialogs/c172p-menu.xml

The FGData walker now also got a flashlight (only NEXT!).
This change makes the cockpit-ALS and walker-compositor flashlight synchron, so switching on the light in the cockpit makes the flashlight on when stepping out of the plane (and vice versa).
Also, as a positive side effect, the walkers (standard) keybind CTRL+F is now operable and switching also the ALS cockpit flashlight.
- - -
- C182 sister PR: https://github.com/HHS81/c182s/pull/558

Flashlight: synchronize with walker flashlight

---

Models/Interior/Panel/Instruments/hi/hi.xml
Nasal/avionics.nas
Nasal/c172p.nas
Systems/instrumentation.xml
c172p-main.xml
gui/dialogs/aircraft-dialog.xml

**Update gyro instruments to current "next" enhancements**
This I made "opt-in", so the pilot needs to activate this from the aircraft options menu.
If this is not activated at startup, it will adjust the instruments config to not exhibit
errors. The instruments will work always good, not wander and not tumble; also
they will spinup very fast (few seconds, like previously).
Gyros will have more realistic behaviour:
* HI, AI and TC: the gyro spinup will take longer (about 2-3 minutes).
* HI:
- can be caged now, and when adjusting the disc, it will realistically cage while moving. Cage can be toggled by shift-click on the knob. The knob appears pushed and the tooltip will also report a hint to the user.
- can tumble now with high G loads
- models errors (drift/precession due to latitude …

Update gyro instruments to current "next" enhancements

---

gui/dialogs/aircraft-dialog.xml
gui/dialogs/c172p-about.xml
gui/dialogs/c172p-baggage-weight.xml
gui/dialogs/c172p-fuel-both-tanks.xml
gui/dialogs/c172p-ground-equipment.xml
gui/dialogs/c172p-left-fuel-sample.xml
gui/dialogs/c172p-left-fuel.xml
gui/dialogs/c172p-mooring-parameters.xml
gui/dialogs/c172p-oil-160.xml
gui/dialogs/c172p-oil-180.xml
gui/dialogs/c172p-right-fuel-sample.xml
gui/dialogs/c172p-right-fuel.xml
gui/dialogs/c172p-save.xml
gui/dialogs/immat.xml

This adds a "X" to the dialogs closing button in the top right corner, like Josh recently proposed on the Mailing List.
Fix #1500

Add "X" to aircraft dialog closing buttons (in the window header)

---

Models/Interior/Panel/Instruments/kr87-adf/kr87.xml
Nasal/kr87.nas
c172-sound.xml

Fix #1279 
(by this occasion, I rewrote the internal timer implementation to use the much friendlier `maketimer()` interface)

KR87 ADF: prevent overflow, implement countdown timer and directly setting the active FRQ in FLT/ELT mode

---

Nasal/electrical-fg1000.nas
Nasal/electrical.nas
Nasal/save.nas
Systems/engine.xml
c172p-main.xml
gui/dialogs/aircraft-dialog.xml

Not respecting the starter duty cycle will damage the starter.
Also added a "serviceable" property to the starter, so failure code may hook that up later. 
Starter properties live below '/engines/active-engine/starter'.
The feature can be toggled on in the aircraft options, and is off as default.
POH, 4-26
The melt down is also depending on the cowling temperature.
Current simulation melts the starter after about 25 seconds continuous(!) operation with fair weather.
Values are guessed (and probably too strict to teach the pilot proper technique) - I did not found actual numbers; but tuning this later is very easy.

Starter overheat simulation

---

Models/c172p.xml
c172-sound-multiplayer.xml

Adds engine sound to remote instances in multiplayer, so other c172 can be heard for example when taxiing

Multiplayer engine sound

---

Models/Interior/Panel/c172p-panel/c172p.xml
Models/c172p.xml

Pressing ALT and moving the levers (mousewheel/dragging) gives finer control now.
This simulates throttles friction lock and the mixtures vernier feature.

Add ALT mode to Throttle/Mixture levers and trim wheels

---

Models/Interior/Panel/c172p-panel/c172p.xml
Models/Interior/Panel/c172sp-panel/c172sp.xml
Models/c172p.xml
Systems/ground-effects.xml

Park brake lever should not translate and rotate at once but after another.
- See C182 ticket: https://github.com/HHS81/c182s/issues/596
- Footage: https://www.youtube.com/watch?v=Qz12zUlrZyk

Parking brake-lever animation enhanced

---

Models/Interior/Panel/c172p-panel/c172p.xml
Systems/ground-effects.xml

A property rule filter limits the (optional) rudder-trim, so it is not overrideable by joystick/keyboard bindings anymore.
Fix #1515

Limit rudder-trim by a filter

---

Models/Interior/Panel/Instruments/kma20/kma20.xml
Nasal/kma20.nas
c172p-keyboard.xml
c172p-main.xml
gui/dialogs/aircraft-dialog.xml

Tested OK, should be fine to merge
Fix #1527

Issue 1527 kma20

---

c172p.xml

Currently no aileron trim feedback to yoke. The C172 has an asymetrically mounted wing in order to compensate for roll-forces in cruise. This is simulated by the aileron-trim prop. Aileron _input_ (yoke) should be neutral, when the input device (joystick) is neutral. Also, don't confuse with rudder-trim (which there is an option for).
For disuccsion see: https://github.com/c172p-team/c172p/issues/1471
Fix #1471

Cockpit flight controls react to trim settings

---

Models/c172p.xml

Fixes #1557 
Using the mouse scroll wheel or left/middle mouse down to adjust the throttle was broken by some of the work in #1537. This merge fixes this issue.
It touches a small area the throttle model slider.

Issue 1557
